// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
package TrafficControl;

public class Authentication {
    private int authenticatorId;
    private String authenticatorName;
    private String authenticatorPassword;

    public Authentication(int authenticatorId, String authenticatorName, String authenticatorPassword) {
        this.authenticatorId = authenticatorId;
        this.authenticatorName = authenticatorName;
        this.authenticatorPassword = authenticatorPassword;
    }

    public void manageTraffic(int trafficOperatorId, String trafficOperatorPassword) {
        boolean isAuthenticated = isAuthenticated(trafficOperatorId, trafficOperatorPassword);

        if (isAuthenticated) {
            System.out.println("Authentication successful. Traffic management initiated by " + authenticatorName);
            initiateTrafficManagement();
        } else {
            System.out.println("Authentication failed. Traffic management cannot be initiated.");
        }
    }

    private boolean isAuthenticated(int trafficOperatorId, String trafficOperatorPassword) {
        return this.authenticatorId == trafficOperatorId && this.authenticatorPassword.equals(trafficOperatorPassword);
    }

    private void initiateTrafficManagement() {
        System.out.println("Traffic management logic executed.");
    }
}
