// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
import java.util.ArrayList;
import java.util.List;

public class DataCenter {
    private int dataCenterId;
    private List<String> previousRouteRecords;
    private String currentRouteRecord;
    private List<String> driverViolationRecords;
    private Monitoring monitoring;
    private Authentication authentication;
    private String weatherRecords;
    private List<String> sensorData;
    private List<String> roadInformation;
    private List<String> maintenanceIssues;

    public DataCenter(int dataCenterId) {
        this.dataCenterId = dataCenterId;
        this.previousRouteRecords = new ArrayList<>();
        this.driverViolationRecords = new ArrayList<>();
        this.monitoring = new Monitoring();
        this.authentication = new Authentication();
        this.weatherRecords = "";
        this.sensorData = new ArrayList<>();
        this.roadInformation = new ArrayList<>();
        this.maintenanceIssues = new ArrayList<>();
    }

    public void updateRouteRecord(String routeRecord) {
        previousRouteRecords.add(routeRecord);
        currentRouteRecord = routeRecord;
    }

    public void updateViolationRecord(String driverLicenseId, String violationRecord) {
        driverViolationRecords.add(driverLicenseId + ": " + violationRecord);
    }

    public void updateWeatherReport(String weatherReport) {
        weatherRecords = weatherReport;
    }

    public void receiveSensorData(String data) {
        sensorData.add(data);
    }

    public void updateRoadInformation(String info) {
        roadInformation.add(info);
    }

    public void reportMaintenanceIssue(String issue) {
        maintenanceIssues.add(issue);
    }
}
