// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Maintenance {
    private List<Integer> scheduled;
    private List<Integer> unscheduled;
    private int maintenanceType;
    private int maintenanceId;
    private Date maintenanceDate;

    public Maintenance() {
        this.scheduled = new ArrayList<>();
        this.unscheduled = new ArrayList<>();
    }

    public List<Integer> getScheduled() {
        return scheduled;
    }

    public void setScheduled(List<Integer> scheduled) {
        this.scheduled = scheduled;
    }

    public List<Integer> getUnscheduled() {
        return unscheduled;
    }

    public void setUnscheduled(List<Integer> unscheduled) {
        this.unscheduled = unscheduled;
    }

    public int getMaintenanceType() {
        return maintenanceType;
    }

    public void setMaintenanceType(int maintenanceType) {
        this.maintenanceType = maintenanceType;
    }

    public int getMaintenanceId() {
        return maintenanceId;
    }

    public void setMaintenanceId(int maintenanceId) {
        this.maintenanceId = maintenanceId;
    }

    public Date getMaintenanceDate() {
        return maintenanceDate;
    }

    public void setMaintenanceDate(Date maintenanceDate) {
        this.maintenanceDate = maintenanceDate;
    }

    public void performMaintenance(int sensorId, int maintenanceType, Date maintenanceDate) {
        System.out.println("Performing maintenance for Sensor ID: " + sensorId);
    }

    public List<Integer> getScheduledList() {
        System.out.println("Scheduled Maintenance:");
        return scheduled;
    }

    public List<Integer> getUnscheduledList() {
        System.out.println("Unscheduled Maintenance:");
        return unscheduled;
    }

    public void addScheduledMaintenance(int sensorId) {
        scheduled.add(sensorId);
    }

    public void addUnscheduledMaintenance(int sensorId) {
        unscheduled.add(sensorId);
    }
}
