// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
public class Notification {
    private int notificationId;
    private String notificationDescription;

    public Notification(int notificationId) {
        this.notificationId = notificationId;
        this.notificationDescription = generateNotificationDescription(notificationId);
    }

    private String generateNotificationDescription(int notificationId) {
        switch (notificationId) {
            case 1:
                return "Traffic congestion detected on Highway A.";
            case 2:
                return "Road maintenance scheduled for next week.";
            case 3:
                return "Traffic signal malfunction reported at intersection.";
            default:
                return "Unknown notification.";
        }
    }

    public String displayNotification() {
        System.out.println("Notification ID: " + notificationId);
        System.out.println("Notification Description: " + notificationDescription);
        return notificationDescription;
    }
}
