// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */

public class ParkingSystem {
    private int parkingId;
    private String[] parkingLocations; 

    public ParkingSystem(int parkingId, String[] parkingLocations) {
        this.parkingId = parkingId;
        this.parkingLocations = parkingLocations;
    }
    public String getNearestParkingById(int parkingId) {
        if (parkingId >= 0 && parkingId < parkingLocations.length) {
            return parkingLocations[parkingId];
        } else {
            return "Parking ID " + parkingId + " is not valid.";
        }
    }
    public void testParkingSystem() {
        String[] parkingLocations = {"Parking Lot A", "Parking Lot B", "Parking Lot C", "Parking Lot D"};
        ParkingSystem parkingSystem = new ParkingSystem(123, parkingLocations);

        String nearestParking = parkingSystem.getNearestParkingById(2);
        System.out.println("Nearest parking for ID 2: " + nearestParking);
    }
}
