// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
package TrafficControl;

public class Pedestrian extends TrafficSignal {
    private int pedestrianLocation;
    private boolean isCrossing;
    public Pedestrian(int pedestrianLocation) {
        this.pedestrianLocation = pedestrianLocation;
        this.isCrossing = false; 
    }
    public String isButtonPressed() {
        return "Pedestrian at location " + pedestrianLocation + " pressed the button.";
    }

    public void crossRoad() {
        if (isCrossing) {
            System.out.println("Pedestrian is already crossing the road.");
        } else {
            System.out.println("Pedestrian at location " + pedestrianLocation + " starts crossing the road.");
            isCrossing = true;
            waitForSignalChange();
            isCrossing = false;
            System.out.println("Pedestrian at location " + pedestrianLocation + " has crossed the road.");
        }
    }

    private void waitForSignalChange() {
        System.out.println("Pedestrian at location " + pedestrianLocation + " is waiting for the signal to change...");
        try {
            Thread.sleep(3000); 
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println("Pedestrian signal changed.");
    }
}

