// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
package TrafficControl;

public class TrafficSignal {
    private int signalID;
    private int locationId;
    private int state;
    private Sensor[] sensors;

    public TrafficSignal(int signalID, int locationId, int state, Sensor[] sensors) {
        this.signalID = signalID;
        this.locationId = locationId;
        this.state = state;
        this.sensors = sensors;
    }

    public String changeSignalState(int signalID) {
        String newState = "Green"; 
        this.state = newState.equals("Green") ? 1 : newState.equals("Yellow") ? 2 : 3; 
        return "Signal state changed for signal ID " + signalID + " to " + newState;
    }

    public void timerState() {
        System.out.println("Timer-based state change activated for signal ID " + signalID);
        startTimer(); 
    }

    public void stopTimer() {
        System.out.println("Timer stopped for signal ID " + signalID);
    }

    public void startTimer() {
        System.out.println("Timer started for signal ID " + signalID);
    }

    String isButtonPressed() {
        return "Button status checked for signal ID " + signalID;
    }
}
