// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */

import java.util.Date;

public class WeatherReport {
    private int rainForecast;
    private Date date;
    public WeatherReport(int rainForecast, Date date) {
        this.rainForecast = rainForecast;
        this.date = date;
    }
    public int getRainForecast() {
        return rainForecast;
    }

    public void setRainForecast(int rainForecast) {
        this.rainForecast = rainForecast;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }
}
